services:
  - type: web
    name: callhot
    env: node
    plan: free
    buildCommand: npm install && npm run next:build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

